### ISSUE TITLE
Merge back with original repo?

### ISSUE THREAD

**Issue by danawoodman** [pdfmake/pdfmake#38]
I've been given contributor access to the original repo, is there interest in merging this back into the original repo to have just one project on NPM?  cc @miltador

**Comment by miltador** [comment]
Hi! Great, I am interested in merging back to original, I'll tidy up my changes and will create PRs! After that I think I will rip this repo.22:24, 14 листопада 2016 р., Dana Woodman <notifications@github.com>:I've been given contributor access to the original repo, is there interest in merging this back into the original repo to have just one project on NPM?  cc @miltador

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




-- Надіслано з мобільної програми Яндекс.Пошти

**Comment by danawoodman** [comment]
Awesome @miltador!

**Comment by RPGillespie6** [comment]
So should I file issues here or at the original?

**Comment by danawoodman** [comment]
I would recommend the original repo for now, I've merged a few PRs already

**Comment by danawoodman** [comment]
@miltador do you want collaborator rights on original repo? I think original author would be open to it

**Comment by miltador** [comment]
Done. This fork is now deprecated and I will remove it. Please switch to original repo.
